import type { AuditReport } from "./audit";

export const sampleReport: AuditReport = {
  auditId: "pd_example",
  requestedUrl: "https://example-product.test",
  finalUrl: "https://example-product.test/",
  scannedAt: "2026-07-30T00:00:00.000Z",
  elapsedMs: 1420,
  score: 82,
  summary: { pass: 13, warn: 3, fail: 1 },
  issues: [
    {
      severity: "fail",
      check: "meta-description",
      evidence: "No meta description found",
      fix: "Add a concise meta description that explains the page value.",
    },
    {
      severity: "warn",
      check: "social-image",
      evidence: "og:image is missing",
      fix: "Add an absolute HTTPS og:image URL, ideally 1200×630.",
    },
    {
      severity: "warn",
      check: "structured-data",
      evidence: "No JSON-LD blocks found",
      fix: "Consider relevant JSON-LD when the page represents an organization, product, article, or event.",
    },
    {
      severity: "warn",
      check: "twitter-card",
      evidence: "twitter:card is missing",
      fix: "Add twitter:card so previews render consistently.",
    },
  ],
  checks: [
    { check: "http-status", label: "HTTP status", status: "pass", evidence: "Final response returned HTTP 200" },
    { check: "redirects", label: "Redirect chain", status: "pass", evidence: "No redirects" },
    { check: "title", label: "Page title", status: "pass", evidence: "38 characters: “Acme — Reports without busywork”" },
    {
      check: "meta-description",
      label: "Meta description",
      status: "fail",
      evidence: "No meta description found",
      fix: "Add a concise meta description that explains the page value.",
    },
    { check: "canonical", label: "Canonical URL", status: "pass", evidence: "https://example-product.test/" },
    { check: "document-language", label: "Document language", status: "pass", evidence: 'html lang="en"' },
    { check: "mobile-viewport", label: "Mobile viewport", status: "pass", evidence: "Viewport configured" },
    { check: "primary-heading", label: "Primary heading", status: "pass", evidence: "1 h1 element found" },
    { check: "og-title", label: "Open Graph title", status: "pass", evidence: "og:title is set" },
    { check: "og-description", label: "Open Graph description", status: "pass", evidence: "og:description is set" },
    {
      check: "social-image",
      label: "Social preview image",
      status: "warn",
      evidence: "og:image is missing",
      fix: "Add an absolute HTTPS og:image URL, ideally 1200×630.",
    },
    {
      check: "twitter-card",
      label: "Twitter card",
      status: "warn",
      evidence: "twitter:card is missing",
      fix: "Add twitter:card so previews render consistently.",
    },
    { check: "favicon", label: "Favicon", status: "pass", evidence: "Icon declared: /favicon.svg" },
    { check: "indexability", label: "Indexability", status: "pass", evidence: "No page-level noindex directive" },
    {
      check: "structured-data",
      label: "Structured data",
      status: "warn",
      evidence: "No JSON-LD blocks found",
      fix: "Consider relevant JSON-LD for the page type.",
    },
    { check: "form-labels", label: "Form label heuristic", status: "pass", evidence: "0 of 2 controls lack a label signal" },
    { check: "link-sample", label: "Same-host link sample", status: "pass", evidence: "6 sampled; 0 returned an error" },
  ],
  links: {
    sampled: 6,
    broken: 0,
    results: [
      { url: "https://example-product.test/pricing", status: 200, ok: true },
      { url: "https://example-product.test/docs", status: 200, ok: true },
      { url: "https://example-product.test/about", status: 200, ok: true },
      { url: "https://example-product.test/privacy", status: 200, ok: true },
      { url: "https://example-product.test/terms", status: 200, ok: true },
      { url: "https://example-product.test/contact", status: 200, ok: true },
    ],
  },
  disclaimer:
    "Automated source-level launch heuristics. This is not penetration testing, legal advice, or a complete WCAG accessibility audit.",
};
